何渝宏	客服组	2019.6.11	一次性需求	马上随借随还	移动手机贷	移动手机贷	营销马上随借随还

1、移动手机贷领取马上免息卷(未使用)且马上授信剩余额度在1500元以上的用户
（保留用户姓名、手机号、免息券领取时间和授信额度）
2、移动手机贷领取马上免息券且未申请过马上产品的用户
（保留用户姓名、手机号、免息券领取时间）
3、移动手机贷领取马上免息券且马上已授信，但未提现的用户，剔除需求1的用户
（保留用户姓名、手机号、免息券领取时间和授信额度）

(-----移动手机贷领取马上免息卷未使用且马上授信剩余额度在1500元以上的用户
1.领取免息券
select a1.data_source,
       distinct a1.phone_number as mbl_no
from warehouse_atomic_coupon_code a1
where a1.coupon_type='2'
and substring(a1.tm_smp,1,8) > '20190510'

2.使用免息券（排除）
left outer join
(select distinct b.phone_number as mbl_no
from warehouse_atomic_coupon_record b
where b.status = '1'
and substring(b.tm_smp,1,8) > '20190510') a2
on a2.mbl_no = a1.mbl_no
---
---
---
and a2.mbl_no is null

3.马上授信剩余额度>1500
--3.1马上授信额度'acc_lim'/100
(select distinct mbl_no,
       acc_lim/100 as num1
from warehouse_atomic_msd_review_result_info a
where appral_res = '通过'
and mbl_no is not null) a3

--3.2马上用信额度'prin_bal'/100,取最近时间的数据
(select mbl_no,num2
from 
(select distinct mbl_no,
       prin_bal/100 as num2,
	   Row_Number() OVER (partition by mbl_no ORDER BY msd_return_time desc) rank     
from warehouse_atomic_msd_withdrawals_result_info a
where msd_return_time > '2019-05-10'
and mbl_no is not null) b
where a4.rank = '1')
)

(结果1
-----移动手机贷领取马上免息卷未使用且马上授信剩余额度在1500元以上的用户
select distinct a1.data_source,
       a1.phone_number as mbl_no,
	   a5.name,
	   substring(a1.tm_smp,1,8),
	   a3.num1
from warehouse_atomic_coupon_code a1
left join warehouse_atomic_user_info a5
on a1.phone_number = a5.mbl_no
and a1.data_source = a5.data_source
-----领券
left outer join
(select distinct b.mbl_no
from warehouse_data_user_withdrawals_info b
where b.product_name = '随借随还-马上' 
  and b.cash_time > '2019-05-10'
  and b.data_source = 'sjd') a2
on a1.phone_number = a2.mbl_no
----未提现（未使用）
join 
(select distinct mbl_no,
       acc_lim/100 as num1
from warehouse_atomic_msd_review_result_info a
where appral_res = '通过'
and mbl_no is not null
and data_source = 'sjd') a3
on a1.phone_number = a3.mbl_no
----授信用户+授信额
left join 
(select mbl_no,num2
from 
(select distinct mbl_no,
       prin_bal/100 as num2,
	   Row_Number() OVER (partition by mbl_no ORDER BY msd_return_time desc) rank     
from warehouse_atomic_msd_withdrawals_result_info a
where msd_return_time > '2019-05-10'
and total_amount > '0'
and mbl_no is not null
and data_source = 'sjd') b
where b.rank = '1') a4
on a1.phone_number = a4.mbl_no
----提现用户+用信额
where a1.coupon_type='2'
and a1.data_source = 'sjd'
and substring(a1.tm_smp,1,8) > '20190510'
and a2.mbl_no is null
and a3.num1-a4.num2 >= '1500'
and a1.phone_number NOT IN (SELECT mbl_no FROM warehouse_atomic_smstunsubscribe WHERE eff_flg = '1')
)

(结果2
select distinct a1.data_source,
       a1.phone_number as mbl_no,
	   a5.name,
	   substring(a1.tm_smp,1,8)
from warehouse_atomic_coupon_code a1
left join warehouse_atomic_user_info a5
on a1.phone_number = a5.mbl_no
and a1.data_source = a5.data_source
-----
left outer join
(select distinct mbl_no 
from warehouse_atomic_msd_review_result_info a
where data_source = 'sjd') a3
on a1.phone_number = a3.mbl_no

where a1.coupon_type='2'
and a1.data_source = 'sjd'
and substring(a1.tm_smp,1,8) > '20190510'
and a3.mbl_no is null
and a5.name is not null
and a1.phone_number NOT IN (SELECT mbl_no FROM warehouse_atomic_smstunsubscribe WHERE eff_flg = '1')
)

(--结果3
select distinct a1.data_source,
       a1.phone_number as mbl_no,
	   a5.name,
	   substring(a1.tm_smp,1,8),
	   a3.acc_lim/100 as num1
from warehouse_atomic_coupon_code a1
left join warehouse_atomic_user_info a5
on a1.phone_number = a5.mbl_no
and a1.data_source = a5.data_source
-----
join warehouse_atomic_msd_review_result_info a3
on a1.phone_number = a3.mbl_no

left outer join
(select distinct mbl_no from warehouse_atomic_msd_withdrawals_result_info a
where msd_return_time > '2019-05-10'
and data_source = 'sjd') a4

left outer join
(SELECT mbl_no FROM warehouse_atomic_smstunsubscribe WHERE eff_flg = '1') a6
on a1.phone_number = a6.mbl_no
where a1.coupon_type='2'
and a1.data_source = 'sjd'
and substring(a1.tm_smp,1,8) > '20190510'
and a3.appral_res = '通过'
and a4.mbl_no is null
and a6.mbl_no is null
and a1.phone_number not in ('MTM0MDQwMTgwMzU=',
                            'MTM0MDgzMjc5Nzk=',
                            'MTM0MTEzMjI1NzY=',
                            'MTM0MTM0OTY5ODU=',
                            'MTM0MTMzMzc5MzY=',
                            'MTM0MTg0MTE4ODU=',
                            'MTM0MTkyNzIzODM=',
                            'MTM0MTkyNzIzODM=',
                            'MTM0MjY4NjE0NDQ=',
                            'MTM0MzAxNjgxMzk=',
                            'MTM0MzI3MzM2NjQ=',
                            'MTM0MzIzMzg2Njg=',
                            'MTM0MzU5MzM1MTQ=',
                            'MTM0MzYzNzQ2MzI=',
                            'MTM0Mzg5NDAwNjI=',
                            'MTM0MzgyOTI0NjY=',
                            'MTM0NTY4ODMxNDM=',
                            'MTM0NTk3NTU4NzE=',
                            'MTM0Njg0ODkzOTc=',
                            'MTM0NzYwMDE2MDE=',
                            'MTM0Nzc3MDgyODg=',
                            'MTM0NzcyMTI3Nzc=',
                            'MTM0ODg3ODE3Mzc=',
                            'MTM1MDI1MzYyNDk=',
                            'MTM1MDI5NzMwNzM=',
                            'MTM1MDc1MDM4ODg=',
                            'MTM1MDg2NDAzNzk=',
                            'MTM1MDk4OTA4Mzk=',
                            'MTM1MTA1MDAyNTI=',
                            'MTM1MTE5MzY4OTY=',
                            'MTM1MTQyNDI2NTE=',
                            'MTM1MTUyMzU1Njc=',
                            'MTM1MTY4NDc0MzA=',
                            'MTM1MTYxMjU5ODE=',
                            'MTM1MTc0MTc5MTc=',
                            'MTM1MTg3MzU4ODM=',
                            'MTM1MTkxNjYxMjc=',
                            'MTM1MjEwOTI4OTI=',
                            'MTM1Mjg2NzY5OTI=',
                            'MTM1Mjk0MjAyNzE=',
                            'MTM1MzAwNjU0NDA=',
                            'MTM1MzE1MDQ1NDQ=',
                            'MTM1MzIwMzk5OTk=',
                            'MTM1MzY5MjcyMTQ=',
                            'MTM1MzgwNTUwMTU=',
                            'MTM1NDA3NDYwMTk=',
                            'MTM1NDA3NDYwMTk=',
                            'MTM1NDAzMTI1NzQ=',
                            'MTM1NDE3MDI4NDc=',
                            'MTM1NDE3MDI4NDc=',
                            'MTM1NDI5NTQ3NTY=',
                            'MTM1NDUzNzY0NTE=',
                            'MTM1NDc3NjAxMjA=',
                            'MTM1NDc3NjIwMDc=',
                            'MTM1NDc5MTE2NTQ=',
                            'MTM1NDgwMzgwODU=',
                            'MTM1NDgxMTEwMDI=',
                            'MTM1NTAzNjE3NTM=',
                            'MTM1NTEyNTE0NTA=',
                            'MTM1NTI4Njg1Mzg=',
                            'MTM1NTg5ODQzODY=',
                            'MTM1NTgxMTE1NTM=',
                            'MTM1NTk4OTc4MTg=',
                            'MTM1NjQ1NjMyODA=',
                            'MTM1Njg4ODkyMTY=',
                            'MTM1NjgzMzA0NDQ=',
                            'MTM1NjgzNTk3ODM=',
                            'MTM1NzIzMjYzMDc=',
                            'MTM1Nzg5NTQ1NTU=',
                            'MTM1Nzk4MjU3Njc=',
                            'MTM1ODAyNzIyNTY=',
                            'MTM1ODU3NTk1NTU=',
                            'MTM1ODU5MzQ1NDA=',
                            'MTM1ODY2MTEwMTA=',
                            'MTM1ODYyNjcxNzA=',
                            'MTM1ODc0NDQxODA=',
                            'MTM1ODc1MzcyMjY=',
                            'MTM1ODcxMzQ0OTQ=',
                            'MTM1OTQ0OTU3ODk=',
                            'MTM1OTQxMDM4ODA=',
                            'MTM1OTkzMTI3NTI=',
                            'MTM1OTkzMzQzODg=',
                            'MTM1OTkzODYwNTI=',
                            'MTM2MDA4ODkxODI=',
                            'MTM2MDA4ODkxODI=',
                            'MTM2MDEyMDc2MDk=',
                            'MTM2MDMxNzM1NTQ=',
                            'MTM2MDcwMTU2MDk=',
                            'MTM2MDkwMTMwMTE=',
                            'MTM2MTE2ODYyNzY=',
                            'MTM2MTMwMjI5NDg=',
                            'MTM2MTMzNTEwMjg=',
                            'MTM2MTUxNDc2NTA=',
                            'MTM2MTY4NzUxMjU=',
                            'MTM2MTYzNjk1MDA=',
                            'MTM2MTgwMjk1ODg=',
                            'MTM2MTgwMjk1ODg=',
                            'MTM2MTkwOTA5Mjg=',
                            'MTM2MjA4OTgyMDI=',
                            'MTM2Mjk5ODEzMzQ=',
                            'MTM2MzAwMDI2MjY=',
                            'MTM2MzIzNzIyOTU=',
                            'MTM2MzQyMjAyMzY=',
                            'MTM2MzY2MzQzNTc=',
                            'MTM2MzcyMzY3Mjg=',
                            'MTM2MzcyMzY3Mjg=',
                            'MTM2Mzk5NjIzNDE=',
                            'MTM2NDAxNDQwMDM=',
                            'MTM2NDY4OTY2Nzg=',
                            'MTM2NDgwMTI5Njk=',
                            'MTM2NTQzODY5Njk=',
                            'MTM2NTU5NTk2OTY=',
                            'MTM2NTgwOTI0MzM=',
                            'MTM2NjAwMDE1NjA=',
                            'MTM2NjYxMjUwMzg=',
                            'MTM2NjYxMjUwMzg=',
                            'MTM2Njc4ODc4MTE=',
                            'MTM2NzA2Mzg4NjI=',
                            'MTM2NzcwMDk0MTQ=',
                            'MTM2Nzg5NzIxODI=',
                            'MTM2NzgwMDYwMjM=',
                            'MTM2NzgyMjAwMDU=',
                            'MTM2Nzk3ODk5MTY=',
                            'MTM2ODEyNTEyMzQ=',
                            'MTM2ODI5MjUxNzc=',
                            'MTM2ODU1NTM2MTE=',
                            'MTM2ODgyMDUwMDY=',
                            'MTM2ODkwNjg3NDk=',
                            'MTM2OTE4ODQ4MTg=',
                            'MTM2OTg5NTU1NzY=',
                            'MTM2OTgyMDY3MzQ=',
                            'MTM2OTk0Njc2NTU=',
                            'MTM3MDY1NzA1Nzk=',
                            'MTM3MDY5NjkwOTE=',
                            'MTM3MDYwMzkxOTQ=',
                            'MTM3MDgwODMyMzE=',
                            'MTM3MDgyMzM0NTQ=',
                            'MTM3MTA1NDQzMTI=',
                            'MTM3MTI4NjAwNDY=',
                            'MTM3MTUzNzY5MzI=',
                            'MTM3MTc1Mjg5NzI=',
                            'MTM3MTcwNDUxNzA=',
                            'MTM3MTczODM4MTQ=',
                            'MTM3MjU1ODY2NzY=',
                            'MTM3Mjk3MjgxMDA=',
                            'MTM3MjkyMTIwMjY=',
                            'MTM3MzA1NTM5MjE=',
                            'MTM3MzA4NjYxNjc=',
                            'MTM3MzA4NjYxNjc=',
                            'MTM3MzExNzYxODY=',
                            'MTM3MzI0ODQ2MTc=',
                            'MTM3MzI3MTQxNTQ=',
                            'MTM3MzI3MTQxNTQ=',
                            'MTM3MzIwMTk5Nzg=',
                            'MTM3MzIyNzc5ODk=',
                            'MTM3MzU2MTE1MjA=',
                            'MTM3MzUxODMyOTY=',
                            'MTM3MzUyNjg1NjM=',
                            'MTM3MzUyODAzMTY=',
                            'MTM3MzUzNTY2OTA=',
                            'MTM3NTE2MzAwOTI=',
                            'MTM3NTcwMzk3MDE=',
                            'MTM3NjQ3ODk3NDk=',
                            'MTM3NjY4MDM5MTU=',
                            'MTM3Njg5OTg5OTc=',
                            'MTM3NzA2MjAyNjM=',
                            'MTM3NzA4Nzg4MTg=',
                            'MTM3NzI3NTI0ODg=',
                            'MTM3NzI4Mjc5NTI=',
                            'MTM3Nzc2MjAwNzk=',
                            'MTM3Nzg4MDg2NjY=',
                            'MTM3NzgxMTk5OTA=',
                            'MTM3Nzk1MDg2MDI=',
                            'MTM3ODAzMTkyNzc=',
                            'MTM3ODIyMzkzMzY=',
                            'MTM3ODU4ODk4ODI=',
                            'MTM3ODg4MDcwNzY=',
                            'MTM3OTA4MzQ5MjI=',
                            'MTM3OTQxMzY2Njc=',
                            'MTM3OTU2ODQ1NDM=',
                            'MTM3OTU3MzM2NTc=',
                            'MTM3OTg3ODE3MzE=',
                            'MTM3OTg5MDg3Mzc=',
                            'MTM3OTk1OTIxMDU=',
                            'MTM4MDc1ODMzNzg=',
                            'MTM4MDgwMzg2ODA=',
                            'MTM4MDgwMzg2ODA=',
                            'MTM4MDkxOTcxMjc=',
                            'MTM4MTAxMzM1Njc=',
                            'MTM4MTE4MTQ4NzU=',
                            'MTM4MTEyMjI4NTY=',
                            'MTM4MTIwODE0NDg=',
                            'MTM4MTIzODI2MDM=',
                            'MTM4MTQ4ODY5OTE=',
                            'MTM4MTQyOTAzMTI=',
                            'MTM4MTczMTY2MDY=',
                            'MTM4MTkwNjI0MjM=',
                            'MTM4MjAzNDU0NDM=',
                            'MTM4MjI2NDQyMzY=',
                            'MTM4MjIyNDAzMjg=',
                            'MTM4MjQzNDc1MDI=',
                            'MTM4Mjg0OTUwNTA=',
                            'MTM4MzE2MDIyMjE=',
                            'MTM4MzU0NzYyMjI=',
                            'MTM4MzU5NjczMjQ=',
                            'MTM4MzcyOTkwNjk=',
                            'MTM4MzkxMzM2NjA=',
                            'MTM4NTAxNDgxNzY=',
                            'MTM4NTIxOTEwNjQ=',
                            'MTM4NTU0NzM4ODM=',
                            'MTM4NTU5NjMzMzU=',
                            'MTM4NTYyMDk0OTQ=',
                            'MTM4NTgzNjk3MDU=',
                            'MTM4NTk5ODM4Njk=',
                            'MTM4NTkwOTEzNjM=',
                            'MTM4NTkxNzg3ODc=',
                            'MTM4NTkzNDQzMjY=',
                            'MTM4NjE3NjMzNTg=',
                            'MTM4NjEwMzMzMTM=',
                            'MTM4NjEwMzcwMTQ=',
                            'MTM4NjM5MzU4NjE=',
                            'MTM4NjY2ODU4ODk=',
                            'MTM4Njg3MDgzNjA=',
                            'MTM4Njg4MjE4MDI=',
                            'MTM4NjgyMjE5NjU=',
                            'MTM4NjgzNDk3Nzc=',
                            'MTM4NzE3Nzc5NzM=',
                            'MTM4NzEzNTk0NDQ=',
                            'MTM4Nzg0MDA1NzE=',
                            'MTM4Nzk3MTg4ODI=',
                            'MTM4NzkxMzc3MTM=',
                            'MTM4NzkyNTc2Mzg=',
                            'MTM4ODA0MDU3Njc=',
                            'MTM4ODA1MzIwODg=',
                            'MTM4ODA2MTE4ODU=',
                            'MTM4ODA4NjcxMDY=',
                            'MTM4ODAyNDI1MDA=',
                            'MTM4ODAyNDI1MDA=',
                            'MTM4ODAzODA3Njc=',
                            'MTM4ODE0MjE4NTU=',
                            'MTM4ODE4MjI3Mjc=',
                            'MTM4ODE4OTYzMjg=',
                            'MTM4ODE5MTEwMjA=',
                            'MTM4ODExODIxODI=',
                            'MTM4ODI5MTA1OTg=',
                            'MTM4ODMzNzQwMzc=',
                            'MTM4ODY5ODk1NDg=',
                            'MTM4ODg2NDMzMDM=',
                            'MTM4ODgxMjMxNjI=',
                            'MTM4ODk0MjE5MTk=',
                            'MTM4ODk3Nzc3ODE=',
                            'MTM4ODkzOTMwNTc=',
                            'MTM4OTA2NTMzODA=',
                            'MTM4OTE5NDE5OTE=',
                            'MTM4OTIyNDE1NTU=',
                            'MTM4OTQxMDY3Mjk=',
                            'MTM4OTUwOTIxMzE=',
                            'MTM4OTcwNjU3NzA=',
                            'MTM4OTg0MTczMjE=',
                            'MTM4OTk4NzgzNDU=',
                            'MTM5MDIyNDE0MTE=',
                            'MTM5MDUyOTQ2NTE=',
                            'MTM5MDYwMzY4NDE=',
                            'MTM5MDcwNzAzODg=',
                            'MTM5MDg2OTQwNTA=',
                            'MTM5MDgwMTMzMTI=',
                            'MTM5MDgxNjI5ODE=',
                            'MTM5MDgxNjI5ODE=',
                            'MTM5MTAwNTQzMjY=',
                            'MTM5MTI3NzA4Mzc=',
                            'MTM5MTM2MDIwODk=',
                            'MTM5MTU1NTIzMTE=',
                            'MTM5MTUwNTE5MDU=',
                            'MTM5MTY0MDM3OTM=',
                            'MTM5MTY3NDAxNzY=',
                            'MTM5MTY5NTcyMDM=',
                            'MTM5MTYzOTE0NTI=',
                            'MTM5MTc0NTQxNzc=',
                            'MTM5MTk4NTE3NjY=',
                            'MTM5MjI3MjU4NzY=',
                            'MTM5MjMxNzc3MTc=',
                            'MTM5MjUzMTAzODc=',
                            'MTM5MjUzOTE0Mzg=',
                            'MTM5Mjc0OTkxMTA=',
                            'MTM5Mjc3NzEzMDE=',
                            'MTM5MjgwNTk4MDI=',
                            'MTM5MzA2MTI5Mjk=',
                            'MTM5MzAxNTcxMTc=',
                            'MTM5MzAxNTcxMTc=',
                            'MTM5NDEzODUxNTk=',
                            'MTM5NTAxNzI5MDU=',
                            'MTM5NTAyMTAwMjc=',
                            'MTM5NTg0NDExMDg=',
                            'MTM5NTk4OTgxODg=',
                            'MTM5NTkzMjU1OTY=',
                            'MTM5NjA2Mzg4Mjc=',
                            'MTM5NjAwMDc3Njk=',
                            'MTM5NjE5ODE5NTY=',
                            'MTM5NjY3Mjk1ODg=',
                            'MTM5NjY3OTkwNTU=',
                            'MTM5NzE0MjI3NDg=',
                            'MTM5NzEwMjg4MTk=',
                            'MTM5NzEyMzMyMTA=',
                            'MTM5Nzc5OTM5NjY=',
                            'MTM5NzcyNzI0NjI=',
                            'MTM5NzkwMzI2MTU=',
                            'MTM5ODA0NTIxNjM=',
                            'MTM5ODAzMzE2NjM=',
                            'MTM5ODE3NDMwMDk=',
                            'MTM5ODE4MDMwMTc=',
                            'MTM5ODE4MDMwMTc=',
                            'MTM5ODEzODQ4MDc=',
                            'MTM5ODI2NTE4MTg=',
                            'MTM5ODIxOTE3NTc=',
                            'MTM5ODIxOTE3NTc=',
                            'MTM5ODIxOTI4MTk=',
                            'MTM5ODIzMzcxNTE=',
                            'MTM5ODIzOTM3NjY=',
                            'MTM5ODM3Njk3NjY=',
                            'MTM5ODQ5OTk5Nzk=',
                            'MTM5ODg3MjQ3ODY=',
                            'MTM5ODkxOTA3NjY=',
                            'MTM5OTA1NTQ1NTc=',
                            'MTM5OTAwMDYzNDM=',
                            'MTM5OTAwNjYwNzI=',
                            'MTM5OTAwNjYwNzI=',
                            'MTM5OTAxMjI3MjY=',
                            'MTM5OTAyNzY2OTA=',
                            'MTM5OTQ0MDg1NDg=',
                            'MTM5OTQyODY5Nzg=',
                            'MTM5OTY2ODQzOTc=',
                            'MTM5OTkyMjQ3NzE=',
                            'MTMwMDU2ODIyNzk=',
                            'MTMwMTc2MDM3MjE=',
                            'MTMwMzU0MDE5MjM=',
                            'MTMwNTg5MjY5NzY=',
                            'MTMwNTgwODg3MDM=',
                            'MTMwNjA2NTIyNTk=',
                            'MTMwNjM5MTMyMzk=',
                            'MTMwNzk2MTY2NjM=',
                            'MTMxMzU3MjY2Nzg=',
                            'MTMxNjcxOTk4MzI=',
                            'MTMxODQ4NDY2NDM=',
                            'MTMyMzcxNDc2MTU=',
                            'MTMyMzg3MjY3OTk=',
                            'MTMyNjI5NTQ2ODM=',
                            'MTMyNjkzODg4MTg=',
                            'MTMyODk5MzM4ODg=',
                            'MTMzMDY1Njg4ODA=',
                            'MTMzMTM5MDcwNjg=',
                            'MTMzMTM5MDcwNjg=',
                            'MTMzMTQ0MjIyOTU=',
                            'MTMzMTc5OTQ2MTE=',
                            'MTMzMjg1MDUyMzA=',
                            'MTMzNjU1MTY2Nzc=',
                            'MTMzODc2OTM5OTk=',
                            'MTMzOTgzNzA0MjY=',
                            'MTMzOTgzNzcxMjA=',
                            'MTQ3MTg0MzQyNDg=',
                            'MTQ3NDcyMzE4MDI=',
                            'MTU1MTA5MTU5Nzc=',
                            'MTU1MTU1MTY5NTU=',
                            'MTU1MzU2NzIzNDU=',
                            'MTU1NDAyMDMwODc=',
                            'MTU1NTAyOTY5OTk=',
                            'MTU1Njk1MTc3Nzk=',
                            'MTU1ODY2ODQ0NDk=',
                            'MTU1ODY3MDgwNzE=',
                            'MTU1ODcxOTQ3MjI=',
                            'MTU2MDgyMjE2ODY=',
                            'MTU2NDU2Nzc5MjU=',
                            'MTU2NTAxOTE1MTU=',
                            'MTU2NzY3MzMzMjg=',
                            'MTU2ODQyNTcxNzc=',
                            'MTU3MTQ0MzgwMDg=',
                            'MTU3MzYwMDc4MDg=',
                            'MTU3MzcxMDg2MTU=',
                            'MTU3NTYyODQxODQ=',
                            'MTU3NjMwNTc2NjY=',
                            'MTU3NjQ5MDc4Nzc=',
                            'MTU3NjY4OTEwNDQ=',
                            'MTU3Njc2ODgzNzA=',
                            'MTU3NjcxMTA5MTA=',
                            'MTU3Njk1MDI3NTA=',
                            'MTU3NzA2NDc0ODI=',
                            'MTU3NzkxNTE5MjA=',
                            'MTU4MDA3NTI1ODc=',
                            'MTU4MDE5NzQ0NzY=',
                            'MTU4MDEzMjIzNTI=',
                            'MTU4MDI1NzUzNTA=',
                            'MTU4MDU0MTU3ODM=',
                            'MTU4MDU3OTI0NDc=',
                            'MTU4MDU4NTg2MzE=',
                            'MTU4MDY3NTA4NzM=',
                            'MTU4MDYwMzA1MTA=',
                            'MTU4MDg3NDE4NzU=',
                            'MTU4MDgzODkzMzc=',
                            'MTU4MTA2NTQzNzQ=',
                            'MTU4MTQxODQ3NTE=',
                            'MTU4MTYwOTAwMDk=',
                            'MTU4MTcxNzI1MTU=',
                            'MTU4MjMxOTQ3ODY=',
                            'MTU4Mjc3MTk1NzI=',
                            'MTU4Mjg0ODc1NjE=',
                            'MTU4MjgwMDMxNjg=',
                            'MTU4MjgyNTcxOTY=',
                            'MTU4MzY0ODE1NTg=',
                            'MTU4Mzk3MTgwMDc=',
                            'MTU4NDE5OTg4MTQ=',
                            'MTU4NDg4ODgxMzk=',
                            'MTU4NTA3MTg2Mjc=',
                            'MTU4NTE0MTQwMzU=',
                            'MTU4NTEwNjgyNTA=',
                            'MTU4NTgxOTQyMDY=',
                            'MTU4NTkwMDc2ODA=',
                            'MTU4NTkxNjkzMjM=',
                            'MTU4NjExMTgyMzk=',
                            'MTU4Njc2MjkwMjk=',
                            'MTU4Njg2MDA1ODE=',
                            'MTU4NzA2NTc4NjA=',
                            'MTU4NzQ0MzIxMDg=',
                            'MTU4NzY1Mzk3NDc=',
                            'MTU4Nzc1MjI1NTI=',
                            'MTU4NzcxNjg5ODM=',
                            'MTU4NzkyMTc5NzA=',
                            'MTU4ODA1NDE1NTU=',
                            'MTU4ODAwNTIwMjM=',
                            'MTU4ODE4ODM1ODI=',
                            'MTU4ODExMzM4NTY=',
                            'MTU4ODIwMzk4OTc=',
                            'MTU4ODIyMDMzMzI=',
                            'MTU4ODIzMjI4OTQ=',
                            'MTU4ODQ2MDk2MDE=',
                            'MTU4ODQ3MDQ5MDA=',
                            'MTU4ODcyNjg4ODM=',
                            'MTU4ODgyNzU2NDA=',
                            'MTU4OTI2OTk1ODg=',
                            'MTU4OTM3MTk4MjY=',
                            'MTU4OTY3MDI5NzM=',
                            'MTU4OTgyNzIxNjY=',
                            'MTU5MDA5MDQ5NDQ=',
                            'MTU5MDUxODU5Nzc=',
                            'MTU5MDY2MTMyMzI=',
                            'MTU5MDY3ODA1Mzc=',
                            'MTU5MDYwOTE1OTA=',
                            'MTU5MDYxODczNDA=',
                            'MTU5MDc1MzIzMzA=',
                            'MTU5MTA0MTk3NzQ=',
                            'MTU5MTQxOTkxNDA=',
                            'MTU5MTU5MzExNDI=',
                            'MTU5MTU5ODk2OTA=',
                            'MTU5MTc4NzM0MTk=',
                            'MTU5MTgyODM2MzY=',
                            'MTU5MTk5NDAyMTI=',
                            'MTU5MjMzMDQ5ODU=',
                            'MTU5Mjg2OTAzNTU=',
                            'MTU5Mjg5NjA3ODM=',
                            'MTU5MjgzOTc2MTY=',
                            'MTU5MzI3MzYwMzI=',
                            'MTU5MzUyNDM0NTQ=',
                            'MTU5Mzc5Mzk5MTg=',
                            'MTU5MzcxMjE1Njk=',
                            'MTU5Mzk5MjcxOTk=',
                            'MTU5MzkxODI2Nzk=',
                            'MTU5NDAxODc4MjI=',
                            'MTU5NDIxNTUyNTI=',
                            'MTU5NDIzMzM3NTQ=',
                            'MTU5NDMwMjg1OTI=',
                            'MTU5NDc3MzQ0NDk=',
                            'MTU5NDk4MjY4OTg=',
                            'MTU5NTI0NDA3NzU=',
                            'MTU5NTczNzU3MzY=',
                            'MTU5NjE2MTkyNzI=',
                            'MTU5NjE4MjE4Mzk=',
                            'MTU5NjM1ODMzNzA=',
                            'MTU5NjkzMjYwMjI=',
                            'MTU5NzQ2NjgxODY=',
                            'MTU5NzU2NTYzMjA=',
                            'MTU5NzY0MTExMjA=',
                            'MTU5ODA5NDA1NzY=',
                            'MTU5ODI4MTkwMjk=',
                            'MTU5ODI4MTkwMjk=',
                            'MTU5ODMwMTIwODg=',
                            'MTU5ODY0Nzc2NzQ=',
                            'MTU5ODYyNjIyMTU=',
                            'MTU5ODg1OTgyNTk=',
                            'MTU5OTA0Mjc1Nzc=',
                            'MTU5OTE3OTg1OTE=',
                            'MTU5OTM0NTIwMzA=',
                            'MTU5OTU2MzY2NDc=',
                            'MTU5OTg0NzM3ODk=',
                            'MTUwMDA3NzcyNDI=',
                            'MTUwMDU3NTc2MTg=',
                            'MTUwMDg5NjcyMTQ=',
                            'MTUwMDgxMTg4Mjc=',
                            'MTUwMDgxMTg4Mjc=',
                            'MTUwMTM0NzMzMjM=',
                            'MTUwMTU3NjM3NjU=',
                            'MTUwMTg3MjI5Nzg=',
                            'MTUwMTgxMzgwOTM=',
                            'MTUwMTkyNDY5ODc=',
                            'MTUwMjEwMjExNzI=',
                            'MTUwMzY1NjY2NzA=',
                            'MTUwMzczODA0MTE=',
                            'MTUwMzgzOTMwMjQ=',
                            'MTUwNDk3ODA4MTc=',
                            'MTUwNTA1MzIyNTE=',
                            'MTUwNTUxNjk0NTA=',
                            'MTUwNTgxMjYyNjY=',
                            'MTUwNTkzMTA3ODE=',
                            'MTUwNjA2ODUwNjg=',
                            'MTUwNjA3NTY0NjI=',
                            'MTUwNjE4MzA2Njk=',
                            'MTUwNjY4OTk5NTI=',
                            'MTUwNjcwNjkxNDc=',
                            'MTUwNjg3NTI5MTg=',
                            'MTUwNzQwNDk5MDI=',
                            'MTUwNzkwMjAzMTU=',
                            'MTUwODI1MzEyMTU=',
                            'MTUwODcxNDU0NTE=',
                            'MTUwODk1ODYyODc=',
                            'MTUwOTY3ODAxMjc=',
                            'MTUxMDI4MDE3MjU=',
                            'MTUxMDI4MDE3MjU=',
                            'MTUxMDMwNDcwMTE=',
                            'MTUxMDU4NjUxNTY=',
                            'MTUxMDUxNTQxNjU=',
                            'MTUxMDcwODE0NTA=',
                            'MTUxMTAwMTU2NjY=',
                            'MTUxMTEyNTU5OTI=',
                            'MTUxMTgyMjczMTY=',
                            'MTUxMjk0NjQ0MTY=',
                            'MTUxMjkyOTc5OTc=',
                            'MTUxMzM2MTExNzA=',
                            'MTUxMzczMDc4OTc=',
                            'MTUxMzgwMjYwNTU=',
                            'MTUxNDk1OTI2MjY=',
                            'MTUxNTEzMTE2MTc=',
                            'MTUxNTQ0NTAyMjU=',
                            'MTUxNTc3NzE3NTc=',
                            'MTUxNjA1MjI1MjI=',
                            'MTUxNjA5MDYwOTY=',
                            'MTUxNjAwMzY5OTc=',
                            'MTUxNjczODQ5NDA=',
                            'MTUxNzAwMTI1NTI=',
                            'MTUxNzQ0MzY2MjA=',
                            'MTUxODAxNzAyMTk=',
                            'MTUxODAzOTcwNTg=',
                            'MTUxODEyNDI4MzE=',
                            'MTUxODM4MDA5OTE=',
                            'MTUxODMzNDA5OTk=',
                            'MTUxODQ0MTE5MTY=',
                            'MTUxODQ0NTM1OTk=',
                            'MTUxODQzMzcyMzM=',
                            'MTUxOTMwOTY2NjU=',
                            'MTUxOTMwOTY2NjU=',
                            'MTUxOTMxODgwMDY=',
                            'MTUxOTY2NzcyMDg=',
                            'MTUxOTY2NzcyMDg=',
                            'MTUxOTYzMzMzMzE=',
                            'MTUxOTc1Nzc4MjE=',
                            'MTUyMDA4Nzg5OTE=',
                            'MTUyMDUwMzIyMTk=',
                            'MTUyMDgyMzcwODM=',
                            'MTUyMTUyNjM3ODA=',
                            'MTUyMTYxMjYxMjA=',
                            'MTUyMjA1OTk5MDU=',
                            'MTUyMjU4NTEwMDA=',
                            'MTUyMjU5MzI4MjM=',
                            'MTUyMjg4NDQ3NjA=',
                            'MTUyMjgyODUyMjI=',
                            'MTUyMzg2NzIxNTg=',
                            'MTUyNDgzMjk1NTU=',
                            'MTUyNTc5MjkwMzk=',
                            'MTUyNTcwMzgwNjM=',
                            'MTUyNTg1MDcxNzk=',
                            'MTUyNTk2NjY2MjM=',
                            'MTUyNTk5OTk5NzI=',
                            'MTUyNjA1NTMzNTM=',
                            'MTUyNzIxOTY2MjE=',
                            'MTUyODA2MDA3MDA=',
                            'MTUyODIxOTI5NTU=',
                            'MTUyODQwMzIwMDk=',
                            'MTUyODcxMTAwMzk=',
                            'MTUyODk3MDA3ODg=',
                            'MTUyOTA5Njg4MDc=',
                            'MTUzMDI0NTAwMjM=',
                            'MTUzMDI0NTAwMjM=',
                            'MTUzMTE1MjExMzA=',
                            'MTUzNjcyODIyMjU=',
                            'MTUzNzg5Mzc1NzQ=',
                            'MTUzOTE1NTUwMTc=',
                            'MTUzOTYzNzAzMjE=',
                            'MTY2MDI3MDEwODY=',
                            'MTc2NzQ1MTc1Nzc=',
                            'MTc3MDcwNDE1NjU=',
                            'MTc3MjgxMzk2MzI=',
                            'MTc3NDY1NjczMzM=',
                            'MTc3NTUxNjE4OTE=',
                            'MTc3NzQwMDM1MTQ=',
                            'MTc3ODc4MTY3OTc=',
                            'MTc4MDI1MzEyOTI=',
                            'MTc4MTc3ODIzMTE=',
                            'MTc4NzY2Mzc0Mjc=',
                            'MTczMDE5MzUzMjc=',
                            'MTg0MTgxMzU2Mjg=',
                            'MTg0MjgwNjM0MTE=',
                            'MTg0Mzk3NjcxMjY=',
                            'MTg0Mzk3NjcxMjY=',
                            'MTg1MDgyNTgzMzU=',
                            'MTg1MTg0MTAwMjA=',
                            'MTg1MjMwODYwNzc=',
                            'MTg1NTEyMTM2OTU=',
                            'MTg1NjY2MzYwMjY=',
                            'MTg1Nzc4ODQ3MjQ=',
                            'MTg1ODg1NTIxNTU=',
                            'MTg2MDM3MTk4MzM=',
                            'MTg2MDQ0OTgyODQ=',
                            'MTg2MDkwMjk0NDQ=',
                            'MTg2MTMyMDgzMjE=',
                            'MTg2MjIwMDU5MjI=',
                            'MTg2Mjc5MzQyMTQ=',
                            'MTg2MjgxNzM5Mzg=',
                            'MTg2MzQ4MTYzODY=',
                            'MTg2NDExNDcwMTc=',
                            'MTg2NDY2OTYwNDI=',
                            'MTg2NTA5MTg5OTk=',
                            'MTg2NTE4ODkxNjM=',
                            'MTg2NTI5NTA3ODQ=',
                            'MTg2NjA4MjAxNjc=',
                            'MTg2NjU4NzUxNTE=',
                            'MTg2NjY1NTAwMjk=',
                            'MTg2NjY2MDAwODk=',
                            'MTg2NjYxNDY4NzM=',
                            'MTg2Njc4ODU1MzA=',
                            'MTg2Njk3OTMzMjI=',
                            'MTg2NzQ4MTYyMDE=',
                            'MTg2OTA1Njc5OTU=',
                            'MTg3MDAxMzM2NjM=',
                            'MTg3MDY0NjY2Nzg=',
                            'MTg3MDgxMzkwNTY=',
                            'MTg3MDgyMjE2NDA=',
                            'MTg3MTA3Nzg5MzY=',
                            'MTg3MTMyOTg3MTI=',
                            'MTg3MTY2MzU4MDY=',
                            'MTg3MTk0ODY3NzY=',
                            'MTg3MTkyNzUzNjU=',
                            'MTg3MjIyMjM2NzU=',
                            'MTg3Mjc4MDc3Nzc=',
                            'MTg3MzE0MDI2NDQ=',
                            'MTg3MzIxODg2NzE=',
                            'MTg3NTA4MjY3Njg=',
                            'MTg3NTYxOTE3NzE=',
                            'MTg3NTcyMzk3MjY=',
                            'MTg3NTg5MzA0OTE=',
                            'MTg3NTgyMjAyNzc=',
                            'MTg3NTk4MzE1NTU=',
                            'MTg3NjAyMjg1MTE=',
                            'MTg3NjE4Nzg0Nzg=',
                            'MTg3NjgyNTg4NjY=',
                            'MTg3NzAxMzg4MTU=',
                            'MTg3NzE4ODcyMzA=',
                            'MTg3NzEwODAzNTk=',
                            'MTg3NzkyNjc4OTM=',
                            'MTg3ODAwMTQ3MTM=',
                            'MTg3ODAwMzgzMTU=',
                            'MTg3ODAxMDUxNTA=',
                            'MTg3ODAxMDUxNTA=',
                            'MTg3ODAxOTc5NzQ=',
                            'MTg3ODAxOTc5NzQ=',
                            'MTg3ODE5MzkxMjg=',
                            'MTg3ODExNzkyMDA=',
                            'MTg3ODI0NzQ3NjI=',
                            'MTg3ODIyMzIyMTA=',
                            'MTg3ODIyMzIyMTA=',
                            'MTg3ODIzNDEzMzY=',
                            'MTg3ODM0NjYwNjM=',
                            'MTg3ODczMDAzNDQ=',
                            'MTg3ODczOTg4ODU=',
                            'MTg3ODkyODg4MTU=',
                            'MTg3OTc3OTI1MzA=',
                            'MTg4MDE4MDYxODA=',
                            'MTg4MDg4NjUwNzc=',
                            'MTg4MDg4NjUwNzc=',
                            'MTg4MTU5NTg1MDk=',
                            'MTg4MjAxNjg2MjA=',
                            'MTg4MjI5MTY5ODY=',
                            'MTg4MjUzNjUzMTE=',
                            'MTg4MjY1NjQyNzY=',
                            'MTg4MjY3NDkxNDc=',
                            'MTg4MjcwNTAwOTA=',
                            'MTg4NDE1MjM1NTU=',
                            'MTg4NDQxMzA0MzE=',
                            'MTg4NDU3Njc3OTI=',
                            'MTg4NDYxOTc2MTU=',
                            'MTg4NTIyNzY5ODE=',
                            'MTg4NTMxMjg4ODU=',
                            'MTg4NTc4NTcxMzk=',
                            'MTg4NTczMjk5MDE=',
                            'MTg4NjUxNTY2Njc=',
                            'MTg4NjgzMjM2MjM=',
                            'MTg4NjgzMzc3MTI=',
                            'MTg4NzY4NDg1ODQ=',
                            'MTg4NzY4NTgwOTA=',
                            'MTg4ODU2MjA4MjI=',
                            'MTg4OTI2MDMzNjA=',
                            'MTg5MDcyMjM5OTU=',
                            'MTg5MjI0MjIwMzM=',
                            'MTg5MzA4NDExNzE=',
                            'MTg5NDE5NzYzNjY=',
                            'MTg5NTkwMjIyNTY=',
                            'MTg5NTkxOTMwODI=',
                            'MTg5NzU3NDIyNzM=',
                            'MTg5OTUyNzc3OTE=',
                            'MTg5OTYyMjE0Mjk=',
                            'MTgwMDgyMTczNzY=',
                            'MTgwMTE1MTMzNjY=',
                            'MTgwMTY2MzA3NTc=',
                            'MTgwMTY2MzA3NTc=',
                            'MTgwNTIzMDk5ODk=',
                            'MTgwNTUyNjE3MTc=',
                            'MTgwNjc2MDk3Mzg=',
                            'MTgwOTUxMzM5ODA=',
                            'MTgxMDE1NTU3OTU=',
                            'MTgxMTI4NTM3NzA=',
                            'MTgxMTM4ODc4NzI=',
                            'MTgxNDU0MzE5OTk=',
                            'MTgxNzI4NTgxMDY=',
                            'MTgxNzM5MjY4OTY=',
                            'MTgxOTI1MDY4NDA=',
                            'MTgyMDA1NTYwNzU=',
                            'MTgyMDAxMDY3MDA=',
                            'MTgyMDAzOTI4MzY=',
                            'MTgyMDIxNzIzODA=',
                            'MTgyMDQwMDMyMjE=',
                            'MTgyMDYwODAwNTA=',
                            'MTgyMTIwMDk0NzU=',
                            'MTgyMTMyNzM2MTU=',
                            'MTgyMTU1OTE5MjA=',
                            'MTgyMjA5ODkzNzg=',
                            'MTgyMjEyMjMxNTY=',
                            'MTgyMjQ0MjgwMzY=',
                            'MTgyMjQwNjk5NDQ=',
                            'MTgyMjQwNjk5NDQ=',
                            'MTgyMjQwNjk5NDQ=',
                            'MTgyMjQwOTE0MjI=',
                            'MTgyMjc2NDEzNTM=',
                            'MTgyMjc2OTYzMjY=',
                            'MTgyMjcyMzE3Njc=',
                            'MTgyMzI0Nzg4ODI=',
                            'MTgyMzMxOTEzMTU=',
                            'MTgyMzczMjYxNjM=',
                            'MTgyMzk1MDU1MzQ=',
                            'MTgyMzkwMzc5MzI=',
                            'MTgyNTM0NzYwOTU=',
                            'MTgyNTc1NjA2OTI=',
                            'MTgyNTcwOTIwMjk=',
                            'MTgyNjE3MjE1NDg=',
                            'MTgyNjY5MTE1MjE=',
                            'MTgyNjgxMjUxNDg=',
                            'MTgyNjgxNjUyMTI=',
                            'MTgyNzA2NDExNzc=',
                            'MTgyNzU3MzM1NTA=',
                            'MTgyODA1ODYxNDc=',
                            'MTgyODAwNTk0MzU=',
                            'MTgyODI2Nzc3ODY=',
                            'MTgyODQ5MjE2MTk=',
                            'MTgyODU2MTYwODI=',
                            'MTgyODYwODMxMzA=',
                            'MTgyODYxMjgzNTM=',
                            'MTgyODc3ODk3MDM=',
                            'MTgyODgwNzM5NzA=',
                            'MTgyOTM0MDAxNjY=',
                            'MTgzMTUwODk3Nzc=',
                            'MTgzMTcwNzQ4Njc=',
                            'MTgzMTgxNTAyMjA=',
                            'MTgzMjAxMjg4ODc=',
                            'MTgzMjAyNDY0NTY=',
                            'MTgzMjEyMDU3ODc=',
                            'MTgzMjQyMjAwMTM=',
                            'MTgzMjYxNzg0MTQ=',
                            'MTgzMjgwODA2NTQ=',
                            'MTgzMzAyODA2MTQ=',
                            'MTgzMzY2Nzc2NTE=',
                            'MTgzNDEyODk5OTM=',
                            'MTgzNDkxNTE5MjU=',
                            'MTgzNTc2MDg3MDU=',
                            'MTgzNTkwMjY4OTg=',
                            'MTgzNjcyNzg4OTM=',
                            'MTgzNjgzMDA3MDU=',
                            'MTgzNzU2ODU1NTA=',
                            'MTgzNzc2Mzk3MzA=',
                            'MTgzODA3MTAzMzg=',
                            'MTgzODQyMjQyNDE=',
                            'MTgzODU4ODg4Njk=',
                            'MTgzODc1NTAwODA=',
                            'MTgzOTQ5MTM0ODI=',
                            'MTgzOTc4NzYzOTI=',
                            'MTgzOTk2ODkxNTg=')

)