CREATE TABLE `p_prod_user_detail_inf` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `prod_user_id` bigint(20) DEFAULT NULL COMMENT '用户产品id',
  `surname` varchar(20) DEFAULT NULL COMMENT '姓名',
  `sex` int(1) DEFAULT NULL COMMENT '性别',
  `marital_status` varchar(10) NOT NULL DEFAULT '' COMMENT '婚姻状况',
  `degree` varchar(10) NOT NULL DEFAULT '' COMMENT '学历',
  `job_type` varchar(10) DEFAULT NULL COMMENT '职业身份',
  `mbl_no` varchar(11) DEFAULT NULL COMMENT '手机号',
  `email` varchar(50) DEFAULT NULL COMMENT '个人邮箱',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `home_area` varchar(20) DEFAULT NULL COMMENT '所在地区',
  `home_address` varchar(100) DEFAULT NULL COMMENT '详细地址',
  `contact_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '联系人姓名',
  `contact_mblno` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '联系人电话',
  `contact_type` varchar(10) NOT NULL DEFAULT '' COMMENT '关系',
  `company_name` varchar(100) DEFAULT NULL COMMENT '公司全称',
  `company_level` varchar(2) DEFAULT NULL COMMENT '公司性质',
  `company_phone` varchar(20) DEFAULT NULL COMMENT '公司电话',
  `company_area` varchar(20) DEFAULT NULL COMMENT '公司所在地区',
  `company_address` varchar(100) DEFAULT NULL COMMENT '公司详细地址',
  `vocation` varchar(20) NOT NULL DEFAULT '' COMMENT '所属行业',
  `job_level` int(2) DEFAULT NULL COMMENT '单位职级',
  `monthly_pay` double(11,2) DEFAULT NULL COMMENT '月公司收入',
  `year_pay` double(11,2) DEFAULT NULL COMMENT '年收入  单位：万元',
  `working_age` varchar(10) NOT NULL DEFAULT '' COMMENT '现公司工作年限',
  `is_security` int(1) DEFAULT NULL COMMENT '现公司是否缴纳社保',
  `is_cpf` int(1) DEFAULT NULL COMMENT '现公司是否缴纳本地公积金',
  `have_car` int(1) DEFAULT NULL COMMENT '名下是否有车',
  `have_house` int(1) DEFAULT NULL COMMENT '名下是否有房',
  `living_status` int(20) DEFAULT NULL COMMENT '现居住状况',
  `loan_usage` varchar(10) DEFAULT NULL COMMENT '借款用途',
  `repaymt_type` varchar(10) DEFAULT NULL COMMENT '还款方式',
  `mon_repaymt_amout` double(11,2) DEFAULT NULL COMMENT '每月最高还款额度',
  `liab_situ` int(2) DEFAULT NULL COMMENT '负债情况',
  `other_loan_situ` int(2) DEFAULT NULL COMMENT '其他网贷借款情况',
  `credit_situ` int(2) DEFAULT NULL COMMENT '征信情况',
  `all_json_info` varchar(4000) DEFAULT NULL COMMENT '全信息json',
  `ext_json_info` varchar(4000) DEFAULT NULL COMMENT '扩展字段',
  `id_card_face` varchar(100) DEFAULT NULL COMMENT '身份证正面,存储fastdfs fileId',
  `id_card_back` varchar(100) DEFAULT NULL COMMENT '身份证背面,存储fastdfs fileId',
  `handheld_idCard` varchar(100) DEFAULT NULL COMMENT '手持身份证照，存储fastdfs fileId',
  `face` varchar(500) DEFAULT NULL COMMENT '活体检测照片,存储fastdfs fileId',
  `ocr_id_card_face` varchar(2000) DEFAULT NULL COMMENT 'ocr识别的身份证正面信息',
  `ocr_id_card_back` varchar(2000) DEFAULT NULL COMMENT 'ocr识别的身份证背面信息',
  `usable` int(1) DEFAULT '0' COMMENT '是否可用 0 可用，1 不可用',
  `credit_status` int(1) DEFAULT '0' COMMENT '是否申请授信 0 未申请 1 已申请',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `loan_amount` varchar(10) DEFAULT NULL COMMENT '借款金额',
  `loan_term` varchar(10) DEFAULT NULL COMMENT '借款期限',
  `family_population` int(2) DEFAULT NULL COMMENT '家庭人口数',
  `open_time` varchar(20) NOT NULL DEFAULT '' COMMENT '营业时间',
  `employee_num` int(10) NOT NULL DEFAULT '0' COMMENT '员工人数',
  `user_qualification` varchar(10) NOT NULL DEFAULT '' COMMENT '用户资质',
  `academic_degree` varchar(10) DEFAULT NULL COMMENT '学位',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx1` (`prod_user_id`,`usable`,`credit_status`)
) ENGINE=InnoDB AUTO_INCREMENT=298538 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='用户产品详情表';